const {
  REACT_APP_AWS_AMAZON,
  REACT_APP_AWS_REGION,
  REACT_APP_AWS_HTTP,
  REACT_APP_BUCKET_NAME,
  REACT_APP_BASE_URL,
} = process.env;

export default {
  REACT_APP_AWS_AMAZON,
  REACT_APP_AWS_REGION,
  REACT_APP_AWS_HTTP,
  REACT_APP_BUCKET_NAME,
  REACT_APP_BASE_URL,
};
